version: '3.9'

services:
  db:
    image: postgres:15.0
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookify
    ports:
      - 5439:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12.10-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:v0.26.0
    volumes:
      - ./prometheus:/prometheus
      - ./prom-alertmanager-data:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
    postgres-network:
        driver: bridge
    rabbitmq-network:
        driver: bridge
    prometheus-network:
        driver: bridge
    grafana-network:
        driver: bridge
    alertmanager-network:
        driver: bridge